import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { poseidon2, poseidon4 } from "poseidon-lite";
import { Group } from "@semaphore-protocol/group";
import * as snarkjs from "snarkjs";
import { identity, leafOf, pk, SEEDS } from "../lib/demo-identities.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const foundry = join(here, "foundry");
const fixtures = join(foundry, "test/fixtures");
const snarkcli = join(here, "../node_modules/snarkjs/cli.js");

mkdirSync(fixtures, { recursive: true });

process.env.PATH = `${process.env.HOME}/.foundry/bin:${process.env.HOME}/.local/bin:${process.env.PATH}`;

function ensureForgeStd() {
  if (existsSync(join(foundry, "lib/forge-std/src/Test.sol"))) return;
  execSync("forge install foundry-rs/forge-std --no-commit", { cwd: foundry, stdio: "inherit" });
}

const alice = identity(SEEDS.alice);
const bob = identity(SEEDS.bob);
const carol = identity(SEEDS.carol);
const tier = 2n;

const aliceLeaf0 = leafOf(alice, tier, 0n);
const aliceLeaf1 = leafOf(alice, tier, 1n);
const bobLeaf = leafOf(bob, tier, 0n);
const carolLeaf = leafOf(carol, tier, 0n);

const group = new Group();
group.addMember(aliceLeaf0);
const rootAfterAlice = group.root;
group.addMember(bobLeaf);
const rootAfterBob = group.root;
group.addMember(carolLeaf);
const rootAfterCarol = group.root;
const revokeProof = group.generateMerkleProof(0);
group.updateMember(0, aliceLeaf1);
const rootAfterRevoke = group.root;

const registryFixture = {
  poseidon2_35: poseidon2([3n, 5n]).toString(),
  poseidon4_1234: poseidon4([1n, 2n, 3n, 4n]).toString(),
  alice: { ...pk(alice), leaf0: aliceLeaf0.toString(), leaf1: aliceLeaf1.toString() },
  bob: { ...pk(bob), leaf0: bobLeaf.toString() },
  carol: { ...pk(carol), leaf0: carolLeaf.toString() },
  rootAfterAlice: rootAfterAlice.toString(),
  rootAfterBob: rootAfterBob.toString(),
  rootAfterCarol: rootAfterCarol.toString(),
  rootAfterRevoke: rootAfterRevoke.toString(),
  revokeSiblings: revokeProof.siblings.map(String),
  revokeIndex: revokeProof.index,
};

writeFileSync(join(fixtures, "registry.json"), JSON.stringify(registryFixture, null, 2));

const proofPath = join(here, "build/proof.json");
const publicPath = join(here, "build/public.json");
const vkeyPath = join(here, "artifacts/vkey.json");
const zkeyPath = join(here, "build/warrant_core_final.zkey");
const wtnsPath = join(here, "build/witness.wtns");

let proof = existsSync(proofPath) ? JSON.parse(readFileSync(proofPath, "utf8")) : null;
let publicSignals = existsSync(publicPath) ? JSON.parse(readFileSync(publicPath, "utf8")) : null;
const vkey = JSON.parse(readFileSync(vkeyPath, "utf8"));

let verifiedJs = false;
if (proof && publicSignals) {
  verifiedJs = await snarkjs.groth16.verify(vkey, publicSignals, proof);
}

if (!verifiedJs && existsSync(zkeyPath) && existsSync(wtnsPath)) {
  const proved = await snarkjs.groth16.prove(zkeyPath, wtnsPath);
  proof = proved.proof;
  publicSignals = proved.publicSignals;
  verifiedJs = await snarkjs.groth16.verify(vkey, publicSignals, proof);
  writeFileSync(proofPath, JSON.stringify(proof));
  writeFileSync(publicPath, JSON.stringify(publicSignals));
}

if (!verifiedJs) {
  console.error("Could not verify or regenerate a warrant_core Groth16 proof");
  process.exit(1);
}

const calldata = await snarkjs.groth16.exportSolidityCallData(proof, publicSignals);
const parsed = JSON.parse(`[${calldata}]`);
const [pA, pB, pC, pubs] = parsed;

function u(x) {
  return `uint256(${x})`;
}

const groth16Sol = `// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {Groth16Verifier} from "../src/WarrantVerifier.sol";

/// Generated by spikes/zk/onchain.mjs from a real warrant_core proof.
/// Do not hand-edit the constants.
contract Groth16VerifierTest is Test {
    Groth16Verifier internal verifier;

    function setUp() public {
        verifier = new Groth16Verifier();
    }

    function _valid()
        internal
        pure
        returns (uint256[2] memory pA, uint256[2][2] memory pB, uint256[2] memory pC, uint256[8] memory pubs)
    {
        pA = [${u(pA[0])}, ${u(pA[1])}];
        pB = [[${u(pB[0][0])}, ${u(pB[0][1])}], [${u(pB[1][0])}, ${u(pB[1][1])}]];
        pC = [${u(pC[0])}, ${u(pC[1])}];
        pubs = [${pubs.map(u).join(", ")}];
    }

    function testValidProofVerifies() public view {
        (uint256[2] memory pA, uint256[2][2] memory pB, uint256[2] memory pC, uint256[8] memory pubs) = _valid();
        assertTrue(verifier.verifyProof(pA, pB, pC, pubs));
    }

    function testTamperedPublicInputFails() public view {
        (uint256[2] memory pA, uint256[2][2] memory pB, uint256[2] memory pC, uint256[8] memory pubs) = _valid();
        pubs[3] = 15; // widened scope
        assertFalse(verifier.verifyProof(pA, pB, pC, pubs));
    }

    function testVerifyProofGas() public {
        (uint256[2] memory pA, uint256[2][2] memory pB, uint256[2] memory pC, uint256[8] memory pubs) = _valid();
        uint256 g = gasleft();
        bool ok = verifier.verifyProof(pA, pB, pC, pubs);
        uint256 used = g - gasleft();
        assertTrue(ok);
        emit log_named_uint("verifyProof_gas", used);
        // Pairing check is well under 400k; keep a ceiling so a regression is loud.
        assertLt(used, 400_000);
        assertGt(used, 150_000);
    }
}
`;

writeFileSync(join(foundry, "test/Groth16Verifier.t.sol"), groth16Sol);

ensureForgeStd();

let forgeOut = "";
let forgeOk = false;
try {
  forgeOut = execSync("forge test -vv --gas-report", {
    cwd: foundry,
    encoding: "utf8",
    maxBuffer: 20_000_000,
  });
  forgeOk = true;
} catch (err) {
  forgeOut = `${err.stdout || ""}\n${err.stderr || err.message}`;
  forgeOk = false;
}

const gasMatch = forgeOut.match(/verifyProof_gas:\s+(\d+)/);
const testsMatch = forgeOut.match(/(\d+) tests passed, (\d+) failed/);
const verifyProofReport = forgeOut.match(
  /\|\s+verifyProof\s+\|\s+(\d+)\s+\|\s+(\d+)\s+\|\s+(\d+)\s+\|\s+(\d+)\s+\|\s+(\d+)\s+\|/,
);

const result = {
  jsGroth16Verified: verifiedJs,
  nPublic: publicSignals.length,
  publicSignals,
  poseidonSolidityMatchInputs: {
    poseidon2_35: registryFixture.poseidon2_35,
    poseidon4_1234: registryFixture.poseidon4_1234,
    aliceLeaf0: registryFixture.alice.leaf0,
  },
  tree: {
    rootAfterAlice: registryFixture.rootAfterAlice,
    rootAfterCarol: registryFixture.rootAfterCarol,
    rootAfterRevoke: registryFixture.rootAfterRevoke,
    revokeSiblings: registryFixture.revokeSiblings,
  },
  forgeOk,
  testsPassed: testsMatch ? Number(testsMatch[1]) : null,
  testsFailed: testsMatch ? Number(testsMatch[2]) : null,
  verifyProofGasLogged: gasMatch ? Number(gasMatch[1]) : null,
  verifyProofGasReportAvg: verifyProofReport ? Number(verifyProofReport[2]) : null,
};

writeFileSync(join(here, "artifacts/onchain-results.json"), JSON.stringify(result, null, 2));
console.log(JSON.stringify(result, null, 2));
if (!forgeOk) {
  console.error(forgeOut.slice(-4000));
}
process.exit(forgeOk ? 0 : 1);
