// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {Groth16Verifier} from "../src/WarrantVerifier.sol";

/// Generated by spikes/zk/onchain.mjs from a real warrant_core proof.
/// Do not hand-edit the constants.
contract Groth16VerifierTest is Test {
    Groth16Verifier internal verifier;

    function setUp() public {
        verifier = new Groth16Verifier();
    }

    function _valid()
        internal
        pure
        returns (uint256[2] memory pA, uint256[2][2] memory pB, uint256[2] memory pC, uint256[8] memory pubs)
    {
        pA = [uint256(0x182e4b40cfc25cf837cc80935e1b53f4843d5cbfbcde600117594b3cceeb6116), uint256(0x2d207f1a506746407a93369c017878580fb7d1b747406f2a0dabf29c298f9139)];
        pB = [[uint256(0x2ef36cba5c6da2d80522af82bd78c2a76831a8680dfd0bce7535fc989484d6d2), uint256(0x14a7363716f5398170692cdb2dab5e3f7c8f6b15fd6caf3d8ca00ffea051046e)], [uint256(0x088c605928dd6a50b44c6773a84f08031e4b7bea442b86437ded2c3eb74b50e3), uint256(0x0c20b6b5b0b5d0f1c9edbf9145fda957eedb94fc2606f66bc4b580159e166831)]];
        pC = [uint256(0x22949d62348031c0f4aeef96f4ab6ea974253e136ceefffe99df761c2610839d), uint256(0x2d1661c683b809a014052e3e2ff29be727011ea68b497b84d66220386260cfe7)];
        pubs = [uint256(0x300d840b0ca8da33b81dc6cf29308b78bdae68bcbd25f768b472bfb83ce04e51), uint256(0x0000000000000000000000000000000000000000000000000000000000000063), uint256(0x0d8af4a7d4bb4a41b8f08b1b38247602f708d8a01f14918cd21ff16fc6cc72f2), uint256(0x0000000000000000000000000000000000000000000000000000000000000001), uint256(0x0000000000000000000000000000000000000000000000000000000000030d40), uint256(0x000000000000000000000000000000000000000000000000000000006a984084), uint256(0x0000000000000000000000000000000000000000000000000000000000000002), uint256(0x00000000000000000000000000000000000000000000000000000000075bcd15)];
    }

    function testValidProofVerifies() public view {
        (uint256[2] memory pA, uint256[2][2] memory pB, uint256[2] memory pC, uint256[8] memory pubs) = _valid();
        assertTrue(verifier.verifyProof(pA, pB, pC, pubs));
    }

    function testTamperedPublicInputFails() public view {
        (uint256[2] memory pA, uint256[2][2] memory pB, uint256[2] memory pC, uint256[8] memory pubs) = _valid();
        pubs[3] = 15; // widened scope
        assertFalse(verifier.verifyProof(pA, pB, pC, pubs));
    }

    function testVerifyProofGas() public {
        (uint256[2] memory pA, uint256[2][2] memory pB, uint256[2] memory pC, uint256[8] memory pubs) = _valid();
        uint256 g = gasleft();
        bool ok = verifier.verifyProof(pA, pB, pC, pubs);
        uint256 used = g - gasleft();
        assertTrue(ok);
        emit log_named_uint("verifyProof_gas", used);
        // Pairing check is well under 400k; keep a ceiling so a regression is loud.
        assertLt(used, 400_000);
        assertGt(used, 150_000);
    }
}
