/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/carbon-g10.ts
 * Command: astryx theme build theme/carbon-g10.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.0.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const carbonG10Theme: DefinedTheme;
