// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

/// @dev Generated by `snarkjs zkey export solidityverifier`. DO NOT EDIT.
/// Placeholder until WP2 exports the real verifier.
contract WarrantVerifier {
    function verifyProof(
        uint256[2] calldata,
        uint256[2][2] calldata,
        uint256[2] calldata,
        uint256[8] calldata
    ) external pure returns (bool) {
        revert("not implemented");
    }
}
